export const NOTICE_STATUSES = [
  'app_quit::core_still_running',
  'clod_config::load_failed',
  'clod_core::update_available',
  'clod_core::updated',
  'clod_sub::fallback_used',
  'clod_sub::url_migrated',
  'config_core::change_error',
  'config_core::change_success',
  'config_validate::boot_error',
  'config_validate::error',
  'config_validate::file_not_found',
  'config_validate::merge_mapping_error',
  'config_validate::merge_syntax_error',
  'config_validate::process_terminated',
  'config_validate::script_error',
  'config_validate::script_missing_main',
  'config_validate::script_syntax_error',
  'config_validate::timeout',
  'config_validate::yaml_mapping_error',
  'config_validate::yaml_read_error',
  'config_validate::yaml_syntax_error',
  'core::binary_changed',
  'core::crashed',
  'core::handoff_failed',
  'core::not_ready',
  'core::port_busy',
  'core::restarted',
  'import_sub_url::error',
  'import_sub_url::ok',
  'reactivate_profiles::error',
  'service::bundle_rejected',
  'service::needs_repair',
  'set_config::error',
  'set_config::ok',
  'sysproxy::core_gave_up',
  'sysproxy::core_not_running',
  'sysproxy::write_failed',
  'tun::adapter_busy',
  'tun::no_rights',
  'tun::no_traffic',
  'tun::rights_declined',
  'tun::service_silent',
  'tun::setup_done',
  'tun::setup_failed',
  'tun::setup_started',
  'tun::start_failed',
  'update::breaking_changes',
  'update_failed',
  'update_with_clash_proxy',
] as const

export type NoticeStatus = (typeof NOTICE_STATUSES)[number]

export const isNoticeStatus = (status: string): status is NoticeStatus =>
  (NOTICE_STATUSES as readonly string[]).includes(status)
