import { useEffect } from 'react'
import useSWR from 'swr'

import { useTauriEvent } from '@/hooks/use-listen'
import { getSentinelReport } from '@/services/cmds'
import {
  noServersReason,
  type NoServersReason,
} from '@/utils/subscription-status'

/**
 * clod: shared answer to "there is nothing to connect to — why?".
 *
 * The reason comes from the subscription data (it stays truthful even when the
 * panel hands out placeholders); the report from the config generation says
 * whether the emptiness is the panel's doing at all. Without that check a
 * template that simply ships no groups would be blamed on the provider.
 *
 * The report describes the last config the core actually accepted (it is
 * committed together with the runtime config, so a failed validation and its
 * rollback never leak a rejected build here), not a profile — and the config
 * is regenerated by far more than a subscription update: a merge-chain edit, a
 * setting that touches the core, a restart. So it is re-read on the same event
 * that refreshes the rest of the core data; keyed on the profile alone it would
 * keep claiming "the panel sent placeholders" long after the user fixed it.
 */
export const useNoServersStatus = (profile?: IProfileItem) => {
  const {
    data: report,
    error,
    mutate,
  } = useSWR(
    profile?.uid ? ['sentinelReport', profile.uid, profile.updated ?? 0] : null,
    getSentinelReport,
    { revalidateOnFocus: false },
  )

  useTauriEvent('verge://refresh-clash-config', () => {
    void mutate()
  })

  useEffect(() => {
    if (error) {
      // Молча это выглядит как «всё в порядке»: список пуст, объяснения нет.
      console.warn('[useNoServersStatus] sentinel report unavailable:', error)
    }
  }, [error])

  const reason: NoServersReason = noServersReason(profile)
  // An expired or exhausted subscription explains itself; anything else needs
  // the config-side confirmation that the panel sent placeholders. Лимит
  // устройств тоже: `subscription-userinfo` в таком ответе здоровый, и без
  // подтверждения баннер мог бы висеть над рабочим списком серверов.
  const needsConfirmation = reason === 'provider' || reason === 'deviceLimit'
  const show =
    Boolean(profile) && (!needsConfirmation || Boolean(report?.only_sentinels))

  return {
    reason,
    show,
    onlySentinels: Boolean(report?.only_sentinels),
    remarks: report?.remarks ?? [],
  }
}
