/**
 * Country detection for proxy node names.
 *
 * The panel gives us nothing but a node name, so the country is guessed from
 * it: a flag emoji, a bare ISO 3166-1 alpha-2 token ("NL-01") or a human name
 * in English or Russian ("Нидерланды", "Germany"). The flag images themselves
 * are bundled with the app (public/flags, the circle-flags set), because emoji
 * flags do not render on Windows at all.
 */

/** Every code we ship a flag for (public/flags/<code>.svg). */
const FLAG_CODES = new Set([
  'ac',
  'ad',
  'ae',
  'af',
  'ag',
  'ai',
  'al',
  'am',
  'an',
  'ao',
  'aq',
  'ar',
  'as',
  'at',
  'au',
  'aw',
  'ax',
  'az',
  'ba',
  'bb',
  'bd',
  'be',
  'bf',
  'bg',
  'bh',
  'bi',
  'bj',
  'bl',
  'bm',
  'bn',
  'bo',
  'bq',
  'br',
  'bs',
  'bt',
  'bv',
  'bw',
  'by',
  'bz',
  'ca',
  'cc',
  'cd',
  'cf',
  'cg',
  'ch',
  'ci',
  'ck',
  'cl',
  'cm',
  'cn',
  'co',
  'cp',
  'cq',
  'cr',
  'cu',
  'cv',
  'cw',
  'cx',
  'cy',
  'cz',
  'de',
  'dg',
  'dj',
  'dk',
  'dm',
  'do',
  'dz',
  'ea',
  'ec',
  'ee',
  'eg',
  'eh',
  'er',
  'es',
  'et',
  'eu',
  'fi',
  'fj',
  'fk',
  'fm',
  'fo',
  'fr',
  'fx',
  'ga',
  'gb',
  'gd',
  'ge',
  'gf',
  'gg',
  'gh',
  'gi',
  'gl',
  'gm',
  'gn',
  'gp',
  'gq',
  'gr',
  'gs',
  'gt',
  'gu',
  'gw',
  'gy',
  'hk',
  'hm',
  'hn',
  'hr',
  'ht',
  'hu',
  'ic',
  'id',
  'ie',
  'il',
  'im',
  'in',
  'io',
  'iq',
  'ir',
  'is',
  'it',
  'je',
  'jm',
  'jo',
  'jp',
  'ke',
  'kg',
  'kh',
  'ki',
  'km',
  'kn',
  'kp',
  'kr',
  'kw',
  'ky',
  'kz',
  'la',
  'lb',
  'lc',
  'li',
  'lk',
  'lr',
  'ls',
  'lt',
  'lu',
  'lv',
  'ly',
  'ma',
  'mc',
  'md',
  'me',
  'mf',
  'mg',
  'mh',
  'mk',
  'ml',
  'mm',
  'mn',
  'mo',
  'mp',
  'mq',
  'mr',
  'ms',
  'mt',
  'mu',
  'mv',
  'mw',
  'mx',
  'my',
  'mz',
  'na',
  'nc',
  'ne',
  'nf',
  'ng',
  'ni',
  'nl',
  'no',
  'np',
  'nr',
  'nu',
  'nz',
  'om',
  'pa',
  'pe',
  'pf',
  'pg',
  'ph',
  'pk',
  'pl',
  'pm',
  'pn',
  'pr',
  'ps',
  'pt',
  'pw',
  'py',
  'qa',
  're',
  'ro',
  'rs',
  'ru',
  'rw',
  'sa',
  'sb',
  'sc',
  'sd',
  'se',
  'sg',
  'sh',
  'si',
  'sj',
  'sk',
  'sl',
  'sm',
  'sn',
  'so',
  'sr',
  'ss',
  'st',
  'su',
  'sv',
  'sx',
  'sy',
  'sz',
  'ta',
  'tc',
  'td',
  'tf',
  'tg',
  'th',
  'tj',
  'tk',
  'tl',
  'tm',
  'tn',
  'to',
  'tr',
  'tt',
  'tv',
  'tw',
  'tz',
  'ua',
  'ug',
  'uk',
  'um',
  'un',
  'us',
  'uy',
  'uz',
  'va',
  'vc',
  've',
  'vg',
  'vi',
  'vn',
  'vu',
  'wf',
  'ws',
  'xk',
  'ye',
  'yt',
  'yu',
  'za',
  'zm',
  'zw',
])

/** Word stems -> code, checked against individual words of the name. */
const NAME_STEMS: [string, string][] = [
  ['NETHERLAND', 'nl'],
  ['НИДЕРЛАНД', 'nl'],
  ['AMSTERDAM', 'nl'],
  ['АМСТЕРДАМ', 'nl'],
  ['HOLLAND', 'nl'],
  ['GERMAN', 'de'],
  ['ГЕРМАН', 'de'],
  ['FRANKFURT', 'de'],
  ['ФРАНКФУРТ', 'de'],
  ['DEUTSCH', 'de'],
  ['FINLAND', 'fi'],
  ['ФИНЛЯНД', 'fi'],
  ['HELSINKI', 'fi'],
  ['ХЕЛЬСИНК', 'fi'],
  ['TURK', 'tr'],
  ['ТУРЦ', 'tr'],
  ['ISTANBUL', 'tr'],
  ['СТАМБУЛ', 'tr'],
  ['UNITED STATES', 'us'],
  ['AMERICA', 'us'],
  ['США', 'us'],
  ['АМЕРИК', 'us'],
  ['UNITED KINGDOM', 'gb'],
  ['BRITAIN', 'gb'],
  ['БРИТАН', 'gb'],
  ['LONDON', 'gb'],
  ['ЛОНДОН', 'gb'],
  ['RUSSIA', 'ru'],
  ['РОССИ', 'ru'],
  ['MOSCOW', 'ru'],
  ['МОСКВ', 'ru'],
  ['FRANCE', 'fr'],
  ['FRENCH', 'fr'],
  ['ФРАНЦ', 'fr'],
  ['PARIS', 'fr'],
  ['ПАРИЖ', 'fr'],
  ['POLAND', 'pl'],
  ['ПОЛЬШ', 'pl'],
  ['WARSAW', 'pl'],
  ['ВАРШАВ', 'pl'],
  ['KAZAKH', 'kz'],
  ['КАЗАХ', 'kz'],
  ['JAPAN', 'jp'],
  ['ЯПОНИ', 'jp'],
  ['TOKYO', 'jp'],
  ['ТОКИО', 'jp'],
  ['HONG KONG', 'hk'],
  ['HONGKONG', 'hk'],
  ['ГОНКОНГ', 'hk'],
  ['SINGAPORE', 'sg'],
  ['СИНГАПУР', 'sg'],
  ['KOREA', 'kr'],
  ['КОРЕ', 'kr'],
  ['SEOUL', 'kr'],
  ['СЕУЛ', 'kr'],
  ['CANADA', 'ca'],
  ['КАНАД', 'ca'],
  ['ITALY', 'it'],
  ['ИТАЛИ', 'it'],
  ['MILAN', 'it'],
  ['МИЛАН', 'it'],
  ['SPAIN', 'es'],
  ['ИСПАН', 'es'],
  ['MADRID', 'es'],
  ['МАДРИД', 'es'],
  ['SWEDEN', 'se'],
  ['ШВЕЦ', 'se'],
  ['STOCKHOLM', 'se'],
  ['СТОКГОЛЬМ', 'se'],
  ['SWITZERLAND', 'ch'],
  ['SWISS', 'ch'],
  ['ШВЕЙЦАР', 'ch'],
  ['ZURICH', 'ch'],
  ['ЦЮРИХ', 'ch'],
  ['AUSTRALIA', 'au'],
  ['АВСТРАЛ', 'au'],
  ['SYDNEY', 'au'],
  ['СИДНЕЙ', 'au'],
  ['AUSTRIA', 'at'],
  ['АВСТРИ', 'at'],
  ['VIENNA', 'at'],
  ['ВЕНА', 'at'],
  ['NORWAY', 'no'],
  ['НОРВЕГ', 'no'],
  ['OSLO', 'no'],
  ['ОСЛО', 'no'],
  ['DENMARK', 'dk'],
  ['ДАТСК', 'dk'],
  ['COPENHAGEN', 'dk'],
  ['КОПЕНГАГЕН', 'dk'],
  ['CZECH', 'cz'],
  ['ЧЕХИ', 'cz'],
  ['PRAGUE', 'cz'],
  ['ПРАГ', 'cz'],
  ['UKRAIN', 'ua'],
  ['УКРАИН', 'ua'],
  ['KYIV', 'ua'],
  ['КИЕВ', 'ua'],
  ['LATVIA', 'lv'],
  ['ЛАТВИ', 'lv'],
  ['RIGA', 'lv'],
  ['РИГА', 'lv'],
  ['LITHUANIA', 'lt'],
  ['ЛИТВ', 'lt'],
  ['VILNIUS', 'lt'],
  ['ВИЛЬНЮС', 'lt'],
  ['ESTONIA', 'ee'],
  ['ЭСТОН', 'ee'],
  ['TALLINN', 'ee'],
  ['ТАЛЛИН', 'ee'],
  ['ISRAEL', 'il'],
  ['ИЗРАИЛ', 'il'],
  ['TEL AVIV', 'il'],
  ['ТЕЛЬ-АВИВ', 'il'],
  ['ARMENIA', 'am'],
  ['АРМЕНИ', 'am'],
  ['GEORGIA', 'ge'],
  ['ГРУЗИ', 'ge'],
  ['TBILISI', 'ge'],
  ['ТБИЛИСИ', 'ge'],
  ['SERBIA', 'rs'],
  ['СЕРБ', 'rs'],
  ['BELGRADE', 'rs'],
  ['БЕЛГРАД', 'rs'],
  ['ROMANIA', 'ro'],
  ['РУМЫН', 'ro'],
  ['BUCHAREST', 'ro'],
  ['БУХАРЕСТ', 'ro'],
  ['BULGARIA', 'bg'],
  ['БОЛГАР', 'bg'],
  ['SOFIA', 'bg'],
  ['СОФИ', 'bg'],
  ['HUNGARY', 'hu'],
  ['ВЕНГР', 'hu'],
  ['BUDAPEST', 'hu'],
  ['БУДАПЕШТ', 'hu'],
  ['GREECE', 'gr'],
  ['ГРЕЦИ', 'gr'],
  ['ATHENS', 'gr'],
  ['АФИН', 'gr'],
  ['PORTUGAL', 'pt'],
  ['ПОРТУГАЛ', 'pt'],
  ['LISBON', 'pt'],
  ['ЛИССАБОН', 'pt'],
  ['IRELAND', 'ie'],
  ['ИРЛАНД', 'ie'],
  ['DUBLIN', 'ie'],
  ['ДУБЛИН', 'ie'],
  ['BELGIUM', 'be'],
  ['БЕЛЬГИ', 'be'],
  ['BRUSSELS', 'be'],
  ['БРЮССЕЛ', 'be'],
  ['INDIA', 'in'],
  ['ИНДИ', 'in'],
  ['MUMBAI', 'in'],
  ['МУМБАИ', 'in'],
  ['BRAZIL', 'br'],
  ['БРАЗИЛ', 'br'],
  ['SAO PAULO', 'br'],
  ['САН-ПАУЛУ', 'br'],
  ['MEXICO', 'mx'],
  ['МЕКСИК', 'mx'],
  ['EMIRATES', 'ae'],
  ['ЭМИРАТ', 'ae'],
  ['DUBAI', 'ae'],
  ['ДУБАЙ', 'ae'],
  ['ОАЭ', 'ae'],
  ['TAIWAN', 'tw'],
  ['ТАЙВАН', 'tw'],
  ['THAILAND', 'th'],
  ['ТАИЛАНД', 'th'],
  ['BANGKOK', 'th'],
  ['БАНГКОК', 'th'],
  ['VIETNAM', 'vn'],
  ['ВЬЕТНАМ', 'vn'],
  ['INDONESIA', 'id'],
  ['ИНДОНЕЗ', 'id'],
  ['MALAYSIA', 'my'],
  ['МАЛАЙЗИ', 'my'],
  ['PHILIPPIN', 'ph'],
  ['ФИЛИППИН', 'ph'],
  ['ARGENTINA', 'ar'],
  ['АРГЕНТИН', 'ar'],
  ['CHILE', 'cl'],
  ['ЧИЛИ', 'cl'],
  ['CHINA', 'cn'],
  ['КИТА', 'cn'],
  ['MOLDOVA', 'md'],
  ['МОЛДОВ', 'md'],
  ['МОЛДАВ', 'md'],
  ['SLOVAKIA', 'sk'],
  ['СЛОВАКИ', 'sk'],
  ['SLOVENIA', 'si'],
  ['СЛОВЕНИ', 'si'],
  ['CROATIA', 'hr'],
  ['ХОРВАТ', 'hr'],
  ['ICELAND', 'is'],
  ['ИСЛАНД', 'is'],
  ['LUXEMBOURG', 'lu'],
  ['ЛЮКСЕМБУРГ', 'lu'],
  ['CYPRUS', 'cy'],
  ['КИПР', 'cy'],
  ['MALTA', 'mt'],
  ['МАЛЬТ', 'mt'],
  ['EGYPT', 'eg'],
  ['ЕГИПЕТ', 'eg'],
  ['ЕГИПТ', 'eg'],
  ['SOUTH AFRICA', 'za'],
  ['ЮАР', 'za'],
  ['NIGERIA', 'ng'],
  ['НИГЕРИ', 'ng'],
  ['AZERBAIJAN', 'az'],
  ['АЗЕРБАЙДЖ', 'az'],
  ['UZBEK', 'uz'],
  ['УЗБЕК', 'uz'],
  ['KYRGYZ', 'kg'],
  ['КИРГИЗ', 'kg'],
  ['КЫРГЫЗ', 'kg'],
  ['TAJIK', 'tj'],
  ['ТАДЖИК', 'tj'],
  ['BELARUS', 'by'],
  ['БЕЛАРУС', 'by'],
  ['БЕЛОРУС', 'by'],
  ['MINSK', 'by'],
  ['МИНСК', 'by'],
]
/** Two-letter tokens that show up in node names but are not countries. */
const TOKEN_STOP_WORDS = new Set(['ip', 'tv', 'vm', 'go', 'ws', 'v2'])

const EMOJI_A = 0x1f1e6
const EMOJI_Z = 0x1f1ff

/** ISO code from a flag emoji inside the name, if any. */
const codeFromEmoji = (name: string): string | undefined => {
  const points = Array.from(name, (char) => char.codePointAt(0) ?? 0)
  for (let i = 0; i < points.length - 1; i += 1) {
    const [a, b] = [points[i], points[i + 1]]
    if (a >= EMOJI_A && a <= EMOJI_Z && b >= EMOJI_A && b <= EMOJI_Z) {
      const code = String.fromCharCode(a - EMOJI_A + 97, b - EMOJI_A + 97)
      if (FLAG_CODES.has(code)) return code
    }
  }
  return undefined
}

/**
 * Guess the ISO 3166-1 alpha-2 code for a node name.
 *
 * Priority: flag emoji, then a human country/city name, then a bare two
 * letter token. `undefined` means "no idea" — the UI shows a neutral icon.
 */
export const countryFromName = (name: string): string | undefined => {
  if (!name) return undefined

  const fromEmoji = codeFromEmoji(name)
  if (fromEmoji) return fromEmoji

  const upper = name.toUpperCase()
  for (const [stem, code] of NAME_STEMS) {
    if (upper.includes(stem)) return code
  }

  // "UK" is what people write, "gb" is what the flag file is called.
  const tokens = upper.split(/[^A-Z0-9]+/u).filter(Boolean)
  for (const token of tokens) {
    if (token === 'UK') return 'gb'
    const lower = token.toLowerCase()
    if (
      token.length === 2 &&
      !TOKEN_STOP_WORDS.has(lower) &&
      FLAG_CODES.has(lower)
    ) {
      return lower
    }
  }

  return undefined
}

/** Path of the bundled flag for a code; the neutral placeholder otherwise. */
export const flagSrc = (code?: string): string =>
  code && FLAG_CODES.has(code) ? `/flags/${code}.svg` : '/flags/xx.svg'

/**
 * Node name without its flag emoji, for rows that draw their own flag —
 * otherwise the list shows the flag twice (and on Windows the emoji
 * degrades into bare letters in front of the name).
 */
export const nameWithoutFlag = (name: string): string =>
  name
    .replace(/[\u{1F1E6}-\u{1F1FF}]{2}/gu, '')
    .replace(/\s{2,}/gu, ' ')
    .trim() || name
