pub mod autostart;
pub mod backup;
pub mod core_updater;
pub mod handle;
pub mod hotkey;
pub mod logger;
pub mod manager;
mod notification;
pub(crate) mod owner_identity;
pub(crate) mod runtime_bundle;
pub mod service;
pub mod sysopt;
pub mod timer;
pub mod traffic_estimate;
pub mod tray;
pub mod updater;
pub mod validate;
pub mod win_uwp;

pub use self::{manager::CoreManager, timer::Timer, updater::SilentUpdater};
